apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaara.fullname" . }}
  labels:
    {{- include "vaara.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vaara.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vaara.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vaara.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: vaara
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: VAARA_HOST
              value: "0.0.0.0"
            - name: VAARA_PORT
              value: "{{ .Values.service.port }}"
            - name: VAARA_LOG_LEVEL
              value: {{ .Values.vaara.logLevel | quote }}
            - name: VAARA_TENANT_ID
              value: {{ .Values.vaara.tenantId | quote }}
            {{- if .Values.vaara.signingKeySecret }}
            - name: VAARA_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.vaara.signingKeySecret }}
                  key: VAARA_SIGNING_KEY
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "vaara.fullname" . }}
      {{- end }}
